version: '3'

services:
  filament-poc-app:
    build:
      context: ./
      dockerfile: Dockerfile-laravel
    container_name: filament-poc-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - LARAVEL_VERSION=12
    networks:
      - database-network-nanicas

networks:
  database-network-nanicas:
    external: true
    name: nans-database-mysql_database-network-nanicas
