# Use a imagem oficial do PHP 8.3.22
FROM php:8.3.22

# Atualizar certificados e GPG antes de tudo
RUN apt-get update && apt-get install -y \
    ca-certificates \
    gnupg \
    dirmngr \
    tzdata

# Atualizar e instalar pacotes necessários
RUN apt-get update && apt-get install -y software-properties-common \
    libzip-dev \
    unzip \
    git \
    libicu-dev \
    libxml2-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libwebp-dev \
    libxpm-dev \
    libonig-dev

# Instalar o Node.js e o NPM
RUN apt-get install -y nodejs npm && \
    npm install -g n && \
    n lts && \
    npm install -g npm@latest

# Instalar extensões PHP
RUN docker-php-ext-install pdo_mysql zip intl mbstring xml bcmath

# Instalar extensão GD
RUN docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp --with-xpm \
    && docker-php-ext-install gd

# Instalar Composer globalmente
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Definir o diretório de trabalho
WORKDIR /var/www/html

# Copiar o script de inicialização do Laravel
COPY init-laravel.sh /var/www/html/init-laravel.sh

# Remover caracteres de quebra de linha do script (Windows)
RUN sed -i 's/\r$//' /var/www/html/init-laravel.sh

# Mudar para usuário root
USER root

# Dar permissão de execução ao arquivo
RUN chmod +x /var/www/html/init-laravel.sh

# Executar o script de inicialização do Laravel
CMD ["sh", "/var/www/html/init-laravel.sh"]
